
const availableTags = [
    "Array",
    "String",
    "Hash Table",
    "Dynamic Programming",
    "Math",
    "Depth-First Search",
    "Sorting",
    "Greedy",
    "Breadth-First Search",
    "Database",
    "Tree",
    "Binary Search",
    "Matrix",
    "Binary Tree",
    "Two Pointers",
    "Bit Manipulation",
    "Stack",
    "Design",
    "Heap (Priority Queue)",
    "Backtracking",
    "Graph",
    "Simulation",
    "Prefix Sum",
    "Sliding Window",
    "Counting",
    "Linked List",
    "Union Find",
    "Recursion",
    "Monotonic Stack",
    "Binary Search Tree",
    "Trie",
    "Ordered Set",
    "Divide and Conquer",
    "Bitmask",
    "Queue",
    "Geometry",
    "Memoization",
    "Enumeration",
    "Game Theory",
    "Topological Sort",
    "Hash Function",
    "Segment Tree",
    "Interactive",
    "Data Stream",
    "Binary Indexed Tree",
    "String Matching",
    "Rolling Hash",
    "Shortest Path",
    "Randomized",
    "Combinatorics",
    "Monotonic Queue",
    "Iterator",
    "Concurrency",
    "Number Theory",
    "Merge Sort",
    "Brainteaser",
    "Probability and Statistics",
    "Doubly-Linked List",
    "Quickselect",
    "Bucket Sort",
    "Minimum Spanning Tree",
    "Counting Sort",
    "Suffix Array",
    "Shell",
    "Line Sweep",
    "Reservoir Sampling",
    "Eulerian Circuit",
    "Strongly Connected Component",
    "Radix Sort",
    "Rejection Sampling",
    "Biconnected Component",
  ];

export default availableTags;
